### PR TITLE
Add Power EC ARN string

### PR DESCRIPTION
**Pull request by Charlie-belmer**
A simple change to include the govcloud vpc ARN's

### CODE REVIEW

**Comment by ALeonard9** [comment]
I would also like to see this change, if it enables Gov-Cloud.

**Comment by berniedurfee-ge** [comment]
I'm on it. I'm working on finalizing a new release for Cago that includes a whole layer of testing. I hope to get that out in the next couple weeks.

**Comment by ALeonard9** [comment]
Thanks Bernie...keep us in the loop. Aviation is starting to push more stuff to gov cloud. This would be a great improvement to a tool we use all the time.

**Comment by berniedurfee-ge** [comment]
This is working as of Cago v2.5.0... which has moved to [GitLab](https://gitlab.com/electric-it/cago)

**Pull request closed without merging**
